# Generated by Django 5.1.4 on 2025-01-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
