# Generated by Django 5.1.4 on 2025-01-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineApp', '0006_alter_medicine_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='brand',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
